//Auto-generated by makefile

#ifndef __PROJINFO_H__
#define __PROJINFO_H__
#include <inttypes.h>

#if (!defined(PROJINFO_SHORT) || !PROJINFO_SHORT)
 uint8_t __attribute__ ((progmem)) \
   header0[] = " /home/bernhard/source/avr-edid-spoofer ";
 uint8_t __attribute__ ((progmem)) \
   header1[] = " Fr Mai 25 01:30:52 CEST 2018 ";
 uint8_t __attribute__ ((progmem)) \
   headerOpt[] = " WDT_DIS=TRUE ";
#else //projInfo Shortened
 uint8_t __attribute__ ((progmem)) \
   const header[] = "LCDreIDer66 2018-05-25 01:30:52";
#endif

//For internal use...
//Currently only usable in main.c
#define PROJ_VER 66
#define COMPILE_YEAR 2018

#endif

